### ISSUE TITLE
Build project error

### ISSUE THREAD

**Issue by funkydevil** [Mobile-Telematics/telematicsSDK-demoapp-flutter-#13]
Hey :)
I have problem with building flutter example project.

Here is problems from console:

> Launching lib/main.dart on iPhone 14 Pro in debug mode...
> main.dart:1
> Xcode build done.                                            6.3s
> Failed to build iOS app
> Swift Compiler Error (Xcode): Unable to load standard library for target 'arm64-apple-ios10.0'
> 
> Swift Compiler Error (Xcode): Module compiled with Swift 5.5.2 cannot be imported by the Swift 5.8.1 compiler: /Users/funkydevil/Downloads/telematicsSDK-demoapp-flutter--main/example/ios/Pods/RaxelPulse/RaxelPulse.framework/Modules/RaxelPulse.swiftmodule/arm64.swiftmodule
> /Users/funkydevil/Downloads/telematicsSDK-demoapp-flutter--main/ios/Classes/SwiftTelematicsSDKPlugin.swift:1:7
> 
> Could not build the application for the simulator.
> Error launching application on iPhone 14 Pro.
> Exited

I was trying to make my own test project with telematics_sdk: ^0.1.1 dependence, but got same error

thanks!

**Comment by telematicsgig** [comment]
Hello Kirill,

Thank you for contacting us.

To address the problem you're facing, please follow these steps:

Ensure that you have the most recent version of the Telematics SDK installed. You can find the latest version in the changelog: [link to the changelog](https://docs.damoov.com/changelog).

It appears that the issue might be related to using a Mac M1. To resolve this, please consult the documentation specifically designed for Mac M1 processors. You can find the necessary information and instructions here: [link to the documentation](https://docs.damoov.com/docs/ios-sdk-for-m1-processors).

These resources should provide you with the guidance needed to overcome the problem you encountered. If you require further assistance, don't hesitate to reach out to us - hello@damoov.com

**Comment by funkydevil** [comment]
Hello :) Thanks for response :)
I am not using Mac M1. I think problem in swift library used by flutter library.
You should be able to reproduce it if try to download and build telematics flutter example

Here is my dependencies files. Looks like everything is up to dated.

pubspec.yml and pubspec.lock files for flutter project. 
pubspec.yml
```
name: telematics_sdk_example
description: Demonstrates how to use the telematics_sdk plugin.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  telematics_sdk: ^0.1.1
    # path: ../

flutter:
  uses-material-design: true
```

pubspec.lock
```
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  characters:
    dependency: transitive
    description:
      name: characters
      sha256: e6a326c8af69605aec75ed6c187d06b349707a27fbff8222ca9cc2cff167975c
      url: "https://pub.dev"
    source: hosted
    version: "1.2.1"
  collection:
    dependency: transitive
    description:
      name: collection
      sha256: cfc915e6923fe5ce6e153b0723c753045de46de1b4d63771530504004a45fae0
      url: "https://pub.dev"
    source: hosted
    version: "1.17.0"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  js:
    dependency: transitive
    description:
      name: js
      sha256: "5528c2f391ededb7775ec1daa69e65a2d61276f7552de2b5f7b8d34ee9fd4ab7"
      url: "https://pub.dev"
    source: hosted
    version: "0.6.5"
  material_color_utilities:
    dependency: transitive
    description:
      name: material_color_utilities
      sha256: d92141dc6fe1dad30722f9aa826c7fbc896d021d792f80678280601aff8cf724
      url: "https://pub.dev"
    source: hosted
    version: "0.2.0"
  meta:
    dependency: transitive
    description:
      name: meta
      sha256: "6c268b42ed578a53088d834796959e4a1814b5e9e164f147f580a386e5decf42"
      url: "https://pub.dev"
    source: hosted
    version: "1.8.0"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  telematics_sdk:
    dependency: "direct main"
    description:
      name: telematics_sdk
      sha256: "3ad6e1164f597978d3db0adfeb0160c14abbcb87a520b7268e3043c85160f636"
      url: "https://pub.dev"
    source: hosted
    version: "0.1.1"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      sha256: "80b3257d1492ce4d091729e3a67a60407d227c27241d6927be0130c98e741803"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.4"
sdks:
  dart: ">=2.17.0-0 <3.0.0"
  flutter: ">=2.0.0"

```



and here is pods files for iOS subproject:

Podfile
```
# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

```

Podfile.lock

```
PODS:
  - Flutter (1.0.0)
  - RaxelPulse (5.16)
  - telematics_sdk (0.1.0):
    - Flutter
    - RaxelPulse

DEPENDENCIES:
  - Flutter (from `Flutter`)
  - telematics_sdk (from `.symlinks/plugins/telematics_sdk/ios`)

SPEC REPOS:
  trunk:
    - RaxelPulse

EXTERNAL SOURCES:
  Flutter:
    :path: Flutter
  telematics_sdk:
    :path: ".symlinks/plugins/telematics_sdk/ios"

SPEC CHECKSUMS:
  Flutter: f04841e97a9d0b0a8025694d0796dd46242b2854
  RaxelPulse: 760e77ad3679ccb16612631336e811ec3927d9d4
  telematics_sdk: 46db6d6529583e3394f89d2a8e60e3c11a1c2c5f

PODFILE CHECKSUM: 57c8aed26fba39d3ec9424816221f294a07c58eb

COCOAPODS: 1.12.1

```
